[package]
name = "protocol-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true
regex.workspace = true
once_cell.workspace = true

[dev-dependencies]
serde.workspace = true
