[package]
name = "protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
bincode.workspace = true
thiserror.workspace = true
ordered-float.workspace = true
num-traits.workspace = true
