[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = {version="1", features=["derive"]}
bincode = "1"
tokio = {version="1", features=["full"]} #TODO: scale down on features
