# Absolute paths to directories with videos in them
root_dirs = [
  "/home/blah/Videos",
  ]

# Port number to await websocket connections on
port = 1337

# Program to run to power off the system
poweroff_exe = "sudo_systemctl_poweroff"

# If true, refresh the cache on program start, once per boot
refresh_cache_boot = false

# Key value pairs of properties for mpv
[mpv.properties]
fullscreen = "yes"
force-window = "immediate"

[spotify]
# The executable to run to start spotify
executable = "spotify"
# Command to run to put spotify in fullscreen by, e.g., moving the cursor and pressing on
# the fullscreen button
fullscreen_exe = "spotify_click_fullscreen"
